import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { IBM_Plex_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'
import './styles.css'

const ibm_plex_sans = IBM_Plex_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ibm_plex_sans',
})
const chivo = Chivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-chivo',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibm_plex_sans.variable + ' ' + chivo.variable}>
        {children}
      </body>
    </html>
  );
}
